### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by recepkocur** [Jean-PhilippeDESCAMPS/JPTabViewController#1]
It works great and easy to customise. But how do I set the badge value for some tab bar item?

**Comment by Jean-PhilippeDESCAMPS** [comment]
This behavior is not planned yet. But it is a good idea to improve my component.

**Comment by recepkocur** [comment]
I hope too, also use custom image...

**Comment by Jean-PhilippeDESCAMPS** [comment]
Thanks for your good ideas !
